settings:
  title: 'Status Page'
  url: 'https://status.securedserveraccess.com' # used for Slack messages
  logo: logo-337x337.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Plex Landing Page # unique identifier
    name: Plex Landing Page
    description: '' # default=empty
    url: 'https://apps.securedserveraccess.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: Homepage
    name: Homepage
    description: ''
    url: 'https://securedserveraccess.com/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Ombi
    name: Ombi
    url: 'https://hfmr.securedserveraccess.com/landingpage'
    method: GET
    expectStatus: 200
    
  - id: Petio
    name: Petio
    url: 'https://hfmr-alt.securedserveraccess.com/#/user'
    method: GET
    expectStatus: 200
    
  - id: Tautulli
    name: Tautulli
    url: 'https://tautulli.securedserveraccess.com/'
    method: GET
    expectStatus: 200
    
  - id: Subsonic radio
    name: Subsonic radio
    url: 'https://radio.securedserveraccess.com/'
    method: GET
    expectStatus: 200
